apiVersion: v1
kind: Service
metadata:
  name: appnode-app
  namespace: appnode
  labels:
    k8s-app: appnode-app
spec:
  selector:
    k8s-app: appnode-app
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
